const { Story } = require('../models');

// Starting data for the Story table
const storydata = [
  {
    title: 'Tyrion ascends the throne',
    description: "Tyrion, after surviving the events of Game of Thrones, is given the opportunity to become king.",
    content: "In the firestorms that devoured King's Landing, a new era was forged. Daenerys, the Breaker of Chains turned tyrant, lay dead amidst the ashes of her ambition. Jon Snow, torn by duty and love, faded into the wilderness. The Great Houses, humbled and shattered, turned their weary eyes to the one man with the cunning to navigate this broken world – Tyrion Lannister. It was no coronation of pomp and cheers. The remaining Lords and Ladies gathered in the skeletal remains of the Red Keep, their voices brittle as they named him King. There were no golden crowns or dragon banners, just the weight of a realm in ruins. Tyrion's reign was no tale of triumphant conquest. It was a reign of shrewd bargains and bitter compromises. With his acid wit and that glint of mischief still hidden in his mismatched eyes, he bound the Seven Kingdoms not through might, but through necessity. The North secured its independence, Sansa Stark crowned Queen in the hardened heart of Winterfell. Yet, they pledged grain and iron in times of crisis, for even the Starks knew winter brought dangers no wall could withstand alone. Dorne, ever smoldering, was appeased with promises of autonomy and a seat on the new Small Council. Tyrion's own rule was marked by a strange sort of pragmatism. He rebuilt King's Landing with wider streets and sturdier homes, a city for the people, not just for lords to squabble in. Brothels were taxed, not outlawed, the gold better spent on ledgers than lechery. He surrounded himself with unlikely advisors: Bronn, now Master of Coin with a surprisingly deft head for numbers; Brienne of Tarth, his towering Kingsguard; and Samwell Tarly, the unassuming scholar who knew more of history's mistakes than any battle commander. The whispers never ceased. They called him the Imp, the Halfman, but fear had faded from the voices. In time, a grudging respect took root.  For crops returned, trade resumed, and while bandits still roamed the wilds, the main roads were safer than they'd been in decades.His was not a reign of songs or great victories. There were no feasts in his honor, nor were his statues erected. Yet, the smallfolk, those eternally trampled beneath the game of thrones, began to breathe easier. Children were born who didn't know the taste of dragon fire, and farmers dared to plow fields untainted by war. Tyrion Lannister died in his bed, old and surprisingly content. There were no cheering crowds at his funeral, only a realm that was a little less broken than when he found it. And amidst the grand histories chronicling wars and weddings, a footnote appeared: And then there was the Imp, who ushered in the Age of Quiet Mending. Perhaps that was the greatest victory of all.",
    series: "Game of Thrones",
    user_id: 1,
  },
  {
    title: 'Cersei joins the Starks',
    description: "Cersei Lannister comes to her senses and joins the Stark effort.",
    content: "The fall of House Lannister was as swift as it was brutal. King's Landing burned, Jaime perished, and Cersei, lioness turned hunted doe, stood before the Starks of Winterfell. Not as a prisoner, but as a supplicant. Sansa, cold as the stones of her ancestral home, studied the woman who had orchestrated her family's ruin. Cersei was stripped of her finery, her arrogance momentarily shattered. Yet, a familiar steeliness flickered in her emerald eyes. 'Survival,' she rasped, golden hair streaked with ash, 'Is the only currency worth fighting for.' The negotiations were as tense as pulled bowstrings. The Northmen clamored for her head, but Jon Snow, the White Wolf, saw something else in Cersei's gaze – a reflection of his own desperate gambles. 'The Night King comes,' he said, his voice ringing in the icy silence of the Great Hall. 'Hatred is a luxury we cannot afford.' It wasn't forgiveness that awaited Cersei, but a grim bargain. In return for her House's remaining forces (what few were left), and her cunning, unyielding mind, she'd be allowed to live. Not as Queen or Lady, but as a weapon to be wielded in the darkness. Cersei, with her acid tongue, could have been a viper in their midst. Yet, stripped of her power, a strange transformation was forced upon her. Her love for her children, twisted as it was, now burned with a desperate, protective fire focused outward. She strategized, not to regain a throne, but to buy just one more sunrise for the ragged alliance. Her knowledge of the South was invaluable, revealing vulnerabilities in Daenerys' forces the North had never anticipated. She traded barbs with Arya, the two of them a prickly, lethal force of grudging, female-driven defiance. She even stood her ground against Sansa, two queens of vastly different courts, learning from each other the hard way. The Battle of the Dawn was painted in blood and starlight. Cersei rallied flagging troops, her voice like a whipcrack. Dragons rained fire, and for a frozen moment, it seemed all hope was lost. Then, a defiant roar tore through the night. It was Cersei, charging, not with golden armor, but with a Valyrian steel dagger. She lunged not at the Night King, but at a wight, its icy eyes mirroring her own. Her scream mingled with the shriek of the dying. She didn't survive the battle.  But as dawn painted the snow-strewn battlefield, her body was found surrounded by the shattered dead, the dagger still clutched in her fist. Cersei Lannister, the lioness who once reveled in the game of thrones, died not for power, but for the fragile, fleeting thing called tomorrow. And in that twisted way, somewhere beneath the icy ground, the Starks finally had their unspoken revenge.",
    series: "Game of Thrones",
    user_id: 1,
  },
];

const seedStory = () => Story.bulkCreate(storydata);

module.exports = seedStory;
